name: Post to Facebook every 3 hours

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run poster script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: node poster.js
